"""Database init.

Revision ID: acf0006f8af9
Revises: 
Create Date: 2021-05-11 08:48:47.268535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf0006f8af9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('locked', sa.SmallInteger(), nullable=True),
    sa.Column('price_multiplier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_locked'), 'countries', ['locked'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('flag', sa.String(length=10), nullable=True),
    sa.Column('map_style', sa.SmallInteger(), nullable=True),
    sa.Column('profile_image', sa.String(length=150), nullable=True),
    sa.Column('country_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('tiles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('available', sa.SmallInteger(), nullable=True),
    sa.Column('tile_class', sa.SmallInteger(), nullable=True),
    sa.Column('for_sale', sa.SmallInteger(), nullable=True),
    sa.Column('user_flag', sa.String(length=10), nullable=True),
    sa.Column('date_changed', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_processed', sa.DateTime(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('total_tiles', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_details')
    op.drop_table('transactions')
    op.drop_table('tiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_locked'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
